// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderRollBackMessage.proto

package com.xdsty.orderbackclient.serializer;

public final class OrderBackMessageProto {
  private OrderBackMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderRollBackMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderRollBackMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 orderId = 1;</code>
     * @return The orderId.
     */
    long getOrderId();

    /**
     * <code>int64 createTime = 2;</code>
     * @return The createTime.
     */
    long getCreateTime();

    /**
     * <code>int64 endTime = 3;</code>
     * @return The endTime.
     */
    long getEndTime();

    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    int getStatus();

    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> 
        getProductListList();
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getProductList(int index);
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    int getProductListCount();
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    java.util.List<? extends com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder> 
        getProductListOrBuilderList();
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder getProductListOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code OrderRollBackMessage}
   */
  public static final class OrderRollBackMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderRollBackMessage)
      OrderRollBackMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderRollBackMessage.newBuilder() to construct.
    private OrderRollBackMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderRollBackMessage() {
      productList_ = java.util.Collections.emptyList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderRollBackMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderRollBackMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              orderId_ = input.readInt64();
              break;
            }
            case 16: {

              createTime_ = input.readInt64();
              break;
            }
            case 24: {

              endTime_ = input.readInt64();
              break;
            }
            case 32: {

              status_ = input.readInt32();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                productList_ = new java.util.ArrayList<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              productList_.add(
                  input.readMessage(com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          productList_ = java.util.Collections.unmodifiableList(productList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_OrderRollBackMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_OrderRollBackMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage.class, com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage.Builder.class);
    }

    public static final int ORDERID_FIELD_NUMBER = 1;
    private long orderId_;
    /**
     * <code>int64 orderId = 1;</code>
     * @return The orderId.
     */
    @Override
    public long getOrderId() {
      return orderId_;
    }

    public static final int CREATETIME_FIELD_NUMBER = 2;
    private long createTime_;
    /**
     * <code>int64 createTime = 2;</code>
     * @return The createTime.
     */
    @Override
    public long getCreateTime() {
      return createTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>int64 endTime = 3;</code>
     * @return The endTime.
     */
    @Override
    public long getEndTime() {
      return endTime_;
    }

    public static final int STATUS_FIELD_NUMBER = 4;
    private int status_;
    /**
     * <code>int32 status = 4;</code>
     * @return The status.
     */
    @Override
    public int getStatus() {
      return status_;
    }

    public static final int PRODUCTLIST_FIELD_NUMBER = 5;
    private java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> productList_;
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    @Override
    public java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> getProductListList() {
      return productList_;
    }
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    @Override
    public java.util.List<? extends com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder> 
        getProductListOrBuilderList() {
      return productList_;
    }
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    @Override
    public int getProductListCount() {
      return productList_.size();
    }
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    @Override
    public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getProductList(int index) {
      return productList_.get(index);
    }
    /**
     * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
     */
    @Override
    public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder getProductListOrBuilder(
        int index) {
      return productList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (orderId_ != 0L) {
        output.writeInt64(1, orderId_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(2, createTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(3, endTime_);
      }
      if (status_ != 0) {
        output.writeInt32(4, status_);
      }
      for (int i = 0; i < productList_.size(); i++) {
        output.writeMessage(5, productList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (orderId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, orderId_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, createTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, status_);
      }
      for (int i = 0; i < productList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, productList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage)) {
        return super.equals(obj);
      }
      com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage other = (com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage) obj;

      if (getOrderId()
          != other.getOrderId()) return false;
      if (getCreateTime()
          != other.getCreateTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getProductListList()
          .equals(other.getProductListList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDERID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrderId());
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      if (getProductListCount() > 0) {
        hash = (37 * hash) + PRODUCTLIST_FIELD_NUMBER;
        hash = (53 * hash) + getProductListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderRollBackMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderRollBackMessage)
        com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_OrderRollBackMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_OrderRollBackMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage.class, com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage.Builder.class);
      }

      // Construct using com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProductListFieldBuilder();
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        orderId_ = 0L;

        createTime_ = 0L;

        endTime_ = 0L;

        status_ = 0;

        if (productListBuilder_ == null) {
          productList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          productListBuilder_.clear();
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_OrderRollBackMessage_descriptor;
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage build() {
        com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage buildPartial() {
        com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage result = new com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage(this);
        int from_bitField0_ = bitField0_;
        result.orderId_ = orderId_;
        result.createTime_ = createTime_;
        result.endTime_ = endTime_;
        result.status_ = status_;
        if (productListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            productList_ = java.util.Collections.unmodifiableList(productList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.productList_ = productList_;
        } else {
          result.productList_ = productListBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage) {
          return mergeFrom((com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage other) {
        if (other == getDefaultInstance()) return this;
        if (other.getOrderId() != 0L) {
          setOrderId(other.getOrderId());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (productListBuilder_ == null) {
          if (!other.productList_.isEmpty()) {
            if (productList_.isEmpty()) {
              productList_ = other.productList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureProductListIsMutable();
              productList_.addAll(other.productList_);
            }
            onChanged();
          }
        } else {
          if (!other.productList_.isEmpty()) {
            if (productListBuilder_.isEmpty()) {
              productListBuilder_.dispose();
              productListBuilder_ = null;
              productList_ = other.productList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              productListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProductListFieldBuilder() : null;
            } else {
              productListBuilder_.addAllMessages(other.productList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long orderId_ ;
      /**
       * <code>int64 orderId = 1;</code>
       * @return The orderId.
       */
      @Override
      public long getOrderId() {
        return orderId_;
      }
      /**
       * <code>int64 orderId = 1;</code>
       * @param value The orderId to set.
       * @return This builder for chaining.
       */
      public Builder setOrderId(long value) {
        
        orderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 orderId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrderId() {
        
        orderId_ = 0L;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 2;</code>
       * @return The createTime.
       */
      @Override
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 2;</code>
       * @param value The createTime to set.
       * @return This builder for chaining.
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 3;</code>
       * @return The endTime.
       */
      @Override
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 3;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 4;</code>
       * @return The status.
       */
      @Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 4;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> productList_ =
        java.util.Collections.emptyList();
      private void ensureProductListIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          productList_ = new java.util.ArrayList<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage>(productList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder> productListBuilder_;

      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> getProductListList() {
        if (productListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(productList_);
        } else {
          return productListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public int getProductListCount() {
        if (productListBuilder_ == null) {
          return productList_.size();
        } else {
          return productListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getProductList(int index) {
        if (productListBuilder_ == null) {
          return productList_.get(index);
        } else {
          return productListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder setProductList(
          int index, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.set(index, value);
          onChanged();
        } else {
          productListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder setProductList(
          int index, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.set(index, builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder addProductList(com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.add(value);
          onChanged();
        } else {
          productListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder addProductList(
          int index, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage value) {
        if (productListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProductListIsMutable();
          productList_.add(index, value);
          onChanged();
        } else {
          productListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder addProductList(
          com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.add(builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder addProductList(
          int index, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder builderForValue) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.add(index, builderForValue.build());
          onChanged();
        } else {
          productListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder addAllProductList(
          Iterable<? extends com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage> values) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          addAll(
              values, productList_);
          onChanged();
        } else {
          productListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder clearProductList() {
        if (productListBuilder_ == null) {
          productList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          productListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public Builder removeProductList(int index) {
        if (productListBuilder_ == null) {
          ensureProductListIsMutable();
          productList_.remove(index);
          onChanged();
        } else {
          productListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder getProductListBuilder(
          int index) {
        return getProductListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder getProductListOrBuilder(
          int index) {
        if (productListBuilder_ == null) {
          return productList_.get(index);  } else {
          return productListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public java.util.List<? extends com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder> 
           getProductListOrBuilderList() {
        if (productListBuilder_ != null) {
          return productListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(productList_);
        }
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder addProductListBuilder() {
        return getProductListFieldBuilder().addBuilder(
            com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder addProductListBuilder(
          int index) {
        return getProductListFieldBuilder().addBuilder(
            index, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .OrderRollBackProductMessage productList = 5;</code>
       */
      public java.util.List<com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder> 
           getProductListBuilderList() {
        return getProductListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder> 
          getProductListFieldBuilder() {
        if (productListBuilder_ == null) {
          productListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder>(
                  productList_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          productList_ = null;
        }
        return productListBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderRollBackMessage)
    }

    // @@protoc_insertion_point(class_scope:OrderRollBackMessage)
    private static final com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage();
    }

    public static com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRollBackMessage>
        PARSER = new com.google.protobuf.AbstractParser<OrderRollBackMessage>() {
      @Override
      public OrderRollBackMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderRollBackMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderRollBackMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderRollBackMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public com.xdsty.orderbackclient.serializer.OrderBackMessageProto.OrderRollBackMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRollBackMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRollBackMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032OrderRollBackMessage.proto\032!OrderRollB" +
      "ackProductMessage.proto\"\217\001\n\024OrderRollBac" +
      "kMessage\022\017\n\007orderId\030\001 \001(\003\022\022\n\ncreateTime\030" +
      "\002 \001(\003\022\017\n\007endTime\030\003 \001(\003\022\016\n\006status\030\004 \001(\005\0221" +
      "\n\013productList\030\005 \003(\0132\034.OrderRollBackProdu" +
      "ctMessageB=\n$com.xdsty.orderbackclient.s" +
      "erializerB\025OrderBackMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.getDescriptor(),
        });
    internal_static_OrderRollBackMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRollBackMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRollBackMessage_descriptor,
        new String[] { "OrderId", "CreateTime", "EndTime", "Status", "ProductList", });
    com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
