// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OrderRollBackProductMessage.proto

package com.xdsty.orderbackclient.serializer;

public final class OrderRollBackProductMessageProto {
  private OrderRollBackProductMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OrderRollBackProductMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:OrderRollBackProductMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 productId = 1;</code>
     * @return The productId.
     */
    long getProductId();

    /**
     * <code>int32 productNum = 2;</code>
     * @return The productNum.
     */
    int getProductNum();
  }
  /**
   * Protobuf type {@code OrderRollBackProductMessage}
   */
  public static final class OrderRollBackProductMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:OrderRollBackProductMessage)
      OrderRollBackProductMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OrderRollBackProductMessage.newBuilder() to construct.
    private OrderRollBackProductMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OrderRollBackProductMessage() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new OrderRollBackProductMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OrderRollBackProductMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              productId_ = input.readInt64();
              break;
            }
            case 16: {

              productNum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_OrderRollBackProductMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_OrderRollBackProductMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.class, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder.class);
    }

    public static final int PRODUCTID_FIELD_NUMBER = 1;
    private long productId_;
    /**
     * <code>int64 productId = 1;</code>
     * @return The productId.
     */
    @Override
    public long getProductId() {
      return productId_;
    }

    public static final int PRODUCTNUM_FIELD_NUMBER = 2;
    private int productNum_;
    /**
     * <code>int32 productNum = 2;</code>
     * @return The productNum.
     */
    @Override
    public int getProductNum() {
      return productNum_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (productId_ != 0L) {
        output.writeInt64(1, productId_);
      }
      if (productNum_ != 0) {
        output.writeInt32(2, productNum_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (productId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, productId_);
      }
      if (productNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, productNum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage)) {
        return super.equals(obj);
      }
      com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage other = (com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage) obj;

      if (getProductId()
          != other.getProductId()) return false;
      if (getProductNum()
          != other.getProductNum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRODUCTID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
      hash = (37 * hash) + PRODUCTNUM_FIELD_NUMBER;
      hash = (53 * hash) + getProductNum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderRollBackProductMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:OrderRollBackProductMessage)
        com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_OrderRollBackProductMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_OrderRollBackProductMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.class, com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.Builder.class);
      }

      // Construct using com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        productId_ = 0L;

        productNum_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_OrderRollBackProductMessage_descriptor;
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage build() {
        com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage buildPartial() {
        com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage result = new com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage(this);
        result.productId_ = productId_;
        result.productNum_ = productNum_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage) {
          return mergeFrom((com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage other) {
        if (other == getDefaultInstance()) return this;
        if (other.getProductId() != 0L) {
          setProductId(other.getProductId());
        }
        if (other.getProductNum() != 0) {
          setProductNum(other.getProductNum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long productId_ ;
      /**
       * <code>int64 productId = 1;</code>
       * @return The productId.
       */
      @Override
      public long getProductId() {
        return productId_;
      }
      /**
       * <code>int64 productId = 1;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(long value) {
        
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 productId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        
        productId_ = 0L;
        onChanged();
        return this;
      }

      private int productNum_ ;
      /**
       * <code>int32 productNum = 2;</code>
       * @return The productNum.
       */
      @Override
      public int getProductNum() {
        return productNum_;
      }
      /**
       * <code>int32 productNum = 2;</code>
       * @param value The productNum to set.
       * @return This builder for chaining.
       */
      public Builder setProductNum(int value) {
        
        productNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 productNum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductNum() {
        
        productNum_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:OrderRollBackProductMessage)
    }

    // @@protoc_insertion_point(class_scope:OrderRollBackProductMessage)
    private static final com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage();
    }

    public static com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OrderRollBackProductMessage>
        PARSER = new com.google.protobuf.AbstractParser<OrderRollBackProductMessage>() {
      @Override
      public OrderRollBackProductMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderRollBackProductMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OrderRollBackProductMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<OrderRollBackProductMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public com.xdsty.orderbackclient.serializer.OrderRollBackProductMessageProto.OrderRollBackProductMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRollBackProductMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRollBackProductMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n!OrderRollBackProductMessage.proto\"D\n\033O" +
      "rderRollBackProductMessage\022\021\n\tproductId\030" +
      "\001 \001(\003\022\022\n\nproductNum\030\002 \001(\005BH\n$com.xdsty.o" +
      "rderbackclient.serializerB OrderRollBack" +
      "ProductMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_OrderRollBackProductMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_OrderRollBackProductMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRollBackProductMessage_descriptor,
        new String[] { "ProductId", "ProductNum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
