project:
  name: api

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: log
server:
  port: 8085
  servlet:
    context-path: /api

dubbo:
  application:
    name: api-consumer
    id: api-consumer
  registry:
    address: nacos://127.0.0.1:8848
    timeout: 10000
  protocol:
    id: dubbo
    name: dubbo

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

audience:
  clientId: algapi
  secret: YWxndXNlcmFwaV8xMDA=
  name: algapi
  accessTokenExpiredMills: 600000
  refreshTokenExpiredMills: 604800000