project:
  name: payservice

server:
  port: 8087

spring:
  my:
   datasource:
      username: '@jdbc.name@'
      password: '@jdbc.password@'
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: '@jdbc.url@'
      initial-size: 5
      max-active: 5
      max-wait: 6000
      min-idle: 5
      pool-prepared-statements: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./log

dubbo:
  application:
    name: pay-service-provider
  registry:
    address: '@dubbo.address@'
    register: true
    timeout: 10000
  protocol:
    name: dubbo
    ssl-enabled: false
    port: 20884
  scan:
    base-packages: com.xdsty.payservice.service
  config-center:
    timeout: 6000
  provider:
    filter: dubboExceptionFilter,-exception


# 配置管理
nacos:
  config:
    server-addr: '@nacos.address@'

seata:
  service-group-name: tx-service-group