project:
  name: orderservice

server:
  port: 8086

spring:
  datasource:
    druid:
      username: root
      password: zhangfuhua123!
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/algorder?characterEncoding=utf-8&useUnicode=true&serverTimezone=UTC
      initial-size: 5
      max-active: 5
      max-wait: 6000
      min-idle: 5
      pool-prepared-statements: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./log

dubbo:
  application:
    name: order-service-provider
  registry:
    address: nacos://127.0.0.1:8848
    register: true
    timeout: 10000
  protocol:
    name: dubbo
    ssl-enabled: false
    port: 20882
  scan:
    base-packages: com.xdsty.orderservice.service
  config-center:
    timeout: 6000
  provider:
    filter: dubboExceptionFilter,-exception


# 配置管理
nacos:
  config:
    server-addr: 127.0.0.1:8848

seata:
  service-group-name: order-service-group

kafka:
  bootstrapServers: 119.23.240.184:9092
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: com.xdsty.orderservice.serializer.KafkaProtobufSerializer
  acks: 1
  blockOnBufferFull: true
  retries: 32