project:
  name: orderbackservice

server:
  port: 9096

spring:
  datasource:
    druid:
      username: '@jdbc.name@'
      password: '@jdbc.password@'
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: '@jdbc.url@'
      initial-size: 5
      max-active: 5
      max-wait: 6000
      min-idle: 5
      pool-prepared-statements: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./log

# ≈‰÷√π‹¿Ì
nacos:
  config:
    server-addr: '@nacos.address@'