project:
  name: orderbackservice

server:
  port: 9096

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 8
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./log

nacos:
  config:
    server-addr: 127.0.0.1:8848

kafka:
  bootstrapServers: '@kafka.servers@'
  keySerializer: org.apache.kafka.common.serialization.StringSerializer
  valueSerializer: com.xdsty.orderbackservice.serializer.KafkaProtobufSerializer
  acks: 1
  blockOnBufferFull: true
  retries: 32